quarkus.http.port=8080

#KAFKA CONFIGURATIONS
%prod.kafka.bootstrap.servers=${KAFKA_SERVER_HOST:"kafka"}:${KAFKA_SERVER_PORT:9092}
%dev.kafka.bootstrap.servers=kafka:9092
mp.messaging.incoming.orchestrator-in.connector=orchestrator-group
mp.messaging.outgoing.orchestrator-out.connector=orchestrator-kafka
mp.messaging.outgoing.orchestrator-out.topics=

