quarkus:
  http:
    port: ${QUARKUS_HTTP_PORT:8092}
  profile: ${QUARKUS_PROFILE:dev}
  application:
    name: ${QUARKUS_APP_NAME:orchestrator_app}
  shutdown:
    timeout: 5
  banner:
    enabled: true
  datasource:
    db-kind: ${QUARKUS_DATASOURCE_KIND:postgresql}
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://10.200.0.202:5432/mcinventory}
